name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=Release . && cat cmake-build-release/compile_commands.json

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-release

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp cmake-build-release/javaparser/parser_main artifacts/javap
          cp cmake-build-release/javarunner/runner artifacts/java

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: jre
          path: artifacts